package com.desperadoboi.imagetopdf.ui.viewer;

public enum ViewerErrorType {
    UNSUPPORTED_LEGACY_XLS,
    UNSUPPORTED_LEGACY_DOC,
    UNSUPPORTED_MACRO_XLSM,
    UNSUPPORTED_DOCUMENT_TYPE,
    PROVIDER_PERMISSION,
    PROVIDER_URI_UNREADABLE,
    GENERIC_TOO_LARGE,
    GENERIC_CORRUPTED,
    SPREADSHEET_TOO_LARGE,
    SPREADSHEET_CORRUPTED,
    SPREADSHEET_ENCRYPTED,
    SPREADSHEET_ACTIVE_CONTENT,
    DOCX_TOO_LARGE,
    DOCX_CORRUPTED,
    DOCX_ENCRYPTED,
    DOCX_UNSUPPORTED,
    CANCELLED
}
